<?xml version="1.0"?>
<package format="3">
  <name>trace_executive</name>
  <version>2.0.0</version>
  <description>The core software for the TRACE mission executive</description>
  <maintainer email="Jean-Pierre.de.la.Croix@jpl.nasa.gov">Jean-Pierre de la Croix</maintainer>
  <license>Caltech</license>
  <url type="website">https://github.jpl.nasa.gov/trace/executive</url>

  <!-- ROS2 build tool dependency -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>boost</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
